### ISSUE TITLE
Compound, unfolded, system (vs.  In-zoomed)

### ISSUE THREAD

**Issue by coevolving** [vainolo/Object-Process-Programming#165]
Thanks for making your work available.  I tried it out (and am still trying to learn the OPM basics).  

When I just downloaded and successfully installed the plugin on Eclipse Mars (Ubuntu 14.04).  I found the tutorial at https://www.opplang.xyz/?page_id=351 .  I assume that the document is out of synch with the current implementation.  

The documentation says that in-zoomed is the only option for a new diagram.  However, when creating a new diagram, the three options are compound, unfolded, and system.

**Comment by vainolo** [comment]
Happy to see you trying it. Note that OPP is a bit different than OPM - not everything in OPM is in OPP and also the other way around.
IN this case the code is not updated to match the documentation - I'll mark this as a bug for fixing. If you find more things, please do let me know.
Thanks!
